export interface ThemeConfig {
  name: string
  // Lighting
  ambientColor: string
  ambientIntensity: number
  fireColor: string
  fireIntensity: number
  fogColor: string
  fogNear: number
  fogFar: number
  background: string
  // Board
  boardColor: string
  boardRoughness: number
  boardMetalness: number
  lightSquareColor: string
  darkSquareColor: string
  cornerColor: string
  throneColor: string
  boardEdgeColor: string
  // Pieces
  attackerColor: string
  attackerEmissive: string
  defenderColor: string
  defenderEmissive: string
  kingColor: string
  kingEmissive: string
  pieceRoughness: number
  pieceMetalness: number
}

export const themes: Record<string, ThemeConfig> = {
  longhouse: {
    name: 'Longhouse',
    ambientColor: '#7a3a00',
    ambientIntensity: 0.4,
    fireColor: '#ff7a20',
    fireIntensity: 4,
    fogColor: '#0d0804',
    fogNear: 16,
    fogFar: 32,
    background: '#0d0804',
    boardColor: '#3a1e08',
    boardRoughness: 0.9,
    boardMetalness: 0.0,
    lightSquareColor: '#7a4a1a',
    darkSquareColor: '#3a1e08',
    cornerColor: '#8b0000',
    throneColor: '#8b4513',
    boardEdgeColor: '#1a0d03',
    attackerColor: '#8b0000',
    attackerEmissive: '#8b2000',
    defenderColor: '#c8a45a',
    defenderEmissive: '#7a5c20',
    kingColor: '#f5d060',
    kingEmissive: '#c8900a',
    pieceRoughness: 0.85,
    pieceMetalness: 0.05,
  },
  clifftop: {
    name: 'Clifftop',
    ambientColor: '#1a2a3a',
    ambientIntensity: 0.5,
    fireColor: '#a8c8e8',
    fireIntensity: 2,
    fogColor: '#0a1520',
    fogNear: 10,
    fogFar: 25,
    background: '#0a1520',
    boardColor: '#2a2a2a',
    boardRoughness: 0.95,
    boardMetalness: 0.1,
    lightSquareColor: '#4a4a4a',
    darkSquareColor: '#252525',
    cornerColor: '#1a3a5a',
    throneColor: '#2a4a6a',
    boardEdgeColor: '#1a1a1a',
    attackerColor: '#2a3a5a',
    attackerEmissive: '#1a3a6a',
    defenderColor: '#8a9aaa',
    defenderEmissive: '#4a6a8a',
    kingColor: '#c8d8e8',
    kingEmissive: '#5a8ab0',
    pieceRoughness: 0.7,
    pieceMetalness: 0.3,
  },
  hoard: {
    name: 'Hoard',
    ambientColor: '#2a1a00',
    ambientIntensity: 0.6,
    fireColor: '#ffd700',
    fireIntensity: 4,
    fogColor: '#0d0800',
    fogNear: 14,
    fogFar: 30,
    background: '#0d0800',
    boardColor: '#f5f0e0',
    boardRoughness: 0.6,
    boardMetalness: 0.1,
    lightSquareColor: '#f5f0e0',
    darkSquareColor: '#d4c8a0',
    cornerColor: '#c8a030',
    throneColor: '#d4a040',
    boardEdgeColor: '#c8a060',
    attackerColor: '#1a0a00',
    attackerEmissive: '#0a0500',
    defenderColor: '#f5f0e0',
    defenderEmissive: '#3d3020',
    kingColor: '#ffd700',
    kingEmissive: '#8b6914',
    pieceRoughness: 0.4,
    pieceMetalness: 0.5,
  },
}
